### PR TITLE
Bring up to date fixing issue #2 in the process!

### PR DESCRIPTION
**Pull request by r0adra93**
Re-added support for categoryLabels
Re-added support for qb-jobs
reworked redundant code and replaced with a single function.

--
server side code reworked
1) made it compatible with qb-jobs
2) removed redundant code
3) tested buying and selling as a customer
2) tested financing and selling as a car dealer
3) tested transferring to another player

You need to test it to do the same.

### CODE REVIEW

**Review by kklrh — APPROVED** [review]
works pretty good

**Comment by Donnyjohn1** [comment]
will not allow me to swap viewable vehicles, no errors in F8 nor in live console

**Comment by Donnyjohn1** [comment]
so when players finance a vehicle, they sometimes get a bug where the vehicle that is supposed to be paid off, shows the pay off price, but actually takes the full payment for the vehicle instead. no errors in F8 nor live console, as well sometimes after purchasing a vehicle it does not spawn it nor teleport you into it when you purchase it, again no F8 errors and no live console errors

**Comment by r0adra93** [comment]
This has nothing to do with this PR. This PR is to bring the code back up to snuff and to alleviate issue #2.

**Review by S33G — CHANGES_REQUESTED** [review]
Too many features/fixes for one PR

**Comment by r0adra93** [comment]
> Too many features/fixes for one PR

I stated what needed to be tested to ensure the changes worked as they all went hand in hand with each other!

By removing one change it breaks the whole chain.

If you want to start paying me to go by your little rules and regulations, please start paying me or let's get this stuff tested and merged in!

**Pull request closed without merging**
